
services:
  # -------------------------------
  # DynamoDB Local
  # -------------------------------
  local-dynamodb:
    image: amazon/dynamodb-local
    container_name: local-dynamodb
    ports:
      - "8000:8000"
    restart: always

  # -------------------------------
  # Redis (with password)
  # -------------------------------
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=MyPassword
    command: ["redis-server", "--requirepass", "MyPassword"]
    restart: always
