global:
  scrape_interval: 15s
  scrape_timeout: 10s   # Add this under global

scrape_configs:
  - job_name: 'redfish_exporter'
    scrape_timeout: 10s  # Also under job
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']
