global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "redfish_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:8000"] # 🔁 Replace with actual IP of Server A
