global:
  scrape_interval: 180s

scrape_configs:
  - job_name: redfish-fastapi
    metrics_path: /probe
    params:
      target: []

    file_sd_configs:
      - files:
          - /etc/prometheus/redfish_targets.json  # path inside container or volume mount
        

    relabel_configs:
      - source_labels: [__param_target]
        target_label: target     
